server:
  port: 0

spring:
  application:
    name: ms-customers
  config:
    import: optional:configserver:http://config-server:8888
eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka/}
  instance:
    preferIpAddress: true