server:
  port: 8080 # El puerto estándar para el Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # (Opcional) Crea rutas automáticas, pero mejor definirlas manuales

      # AQUÍ SE DEFINEN LAS RUTAS
      routes:
        # Ruta para MS-FEES
        - id: ms-fees-route
          uri: lb://MS-FEES  # "lb" significa Load Balancer. Busca "MS-FEES" en Eureka
          predicates:
            - Path=/api/fees/** # Todo lo que empiece por esto va al MS-Fees

        # Ruta para MS-INVENTORY (Ejemplo)
        - id: ms-inventory-route
          uri: lb://ms-inventory #reenvia a MS-INVENTORY, registrado en eureka
          predicates:
            - Path=/api/tools/**

        # Ruta para MS-LOANS (Ejemplo)
        - id: ms-loans-route
          uri: lb://ms-loans
          predicates:
            - Path=/api/loans/**
          filters:
            - StripPrefix=1
        # Ruta para MS-Customers
        - id: ms-customers-route
          uri: lb://ms-customers
          predicates:
            - Path=/api/customers/**
        # Ruta para MS-Kardex
        - id: ms-kardex-route
          uri: lb://ms-kardex
          predicates:
            - Path=/api/kardex/**
        # Ruta para MS-Fees
        - id: ms-fees-route
          uri: lb://ms-fees
          predicates:
            - Path=/api/fee/**

      # CONFIGURACIÓN CORS (CRUCIAL PARA EL FRONTEND)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # En producción cambia esto por la URL de tu frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true